---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Determine running version of swift
  shell: "pgrep -fao swift | sed -r 's_.*(swift-[0-9.]+).*_\\1_'"
  register: running_swift
  delegate_to: "{{ groups['swift_proxy'][0] }}"

- name: Gather swift recon output
  shell: "/openstack/venvs/{{ running_swift.stdout }}/bin/swift-recon -arul --md5"
  register: swiftrecon_result
  delegate_to: "{{ groups['swift_proxy'][0] }}"

- name: Output swift recon stats into text
  template:
    src: "swift_recon.txt.j2"
    dest: "{{ backup_dir }}/swift_recon-{{ datetime_stamp }}.txt"
