---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kibana_apt_repo_url: "http://packages.elastic.co/kibana/4.5/debian"

kibana_apt_repos:
  - { repo: "deb {{ kibana_apt_repo_url }} stable main", state: "present" }

kibana_apt_keys:
  - { url: "http://packages.elastic.co/GPG-KEY-elasticsearch", state: "present" }

kibana_apt_packages:
  - kibana
  - apache2
  - python-passlib

kibana_apache_modules:
  - rewrite
  - ssl
  - proxy
  - proxy_http

elasticsearch_http_port: 9200
elasticsearch_vip: "{{ internal_lb_vip_address }}"

kibana_debug: False
kibana_verbose: True

kibana_app_port: 5601
kibana_ssl_port: 8443

# This is the user:group that kibana runs as
kibana_service_user: kibana
kibana_service_group: root

kibana_server_name: "{{ external_lb_vip_address }}"
kibana_self_signed: true
kibana_log_level: info
kibana_ssl_cert: '/etc/ssl/certs/apache.cert'
kibana_ssl_key: '/etc/ssl/private/apache.key'
kibana_ssl_cert_path: '/etc/ssl/certs'
kibana_ssl_protocol: '{{ ssl_protocol|default("ALL -SSLv2 -SSLv3") }}'
kibana_ssl_cipher_suite: '{{ ssl_cipher_suite|default("ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS") }}'

# Directories to create
kibana_directories:
  - { name: /var/log/kibana, mode: 755 }
