language: python

before_script:
- pip install tox
- pip2 install --force-reinstall 'ansible===1.9.4'
- ansible-galaxy install --role-file=ansible-role-requirements.yml --force --roles-path=/home/travis/build/rcbops/rpc-openstack/rpcd/playbooks/roles

script: tox

notifications:
    email: false

matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=ansible-lint

sudo: false
