rpc_product_releases:
  master:
    maas_release: master
    osa_release: master
    rpc_release: master
  newton:
    maas_release: 1.4.0
    osa_release: 32230e8cd982367940a9b68f65f1e73d6f14d2c4
    rpc_release: r14.6.0
  ocata:
    maas_release: 1.4.0
    osa_release: stable/ocata
    rpc_release: r15.0.0
  pike:
    maas_release: 1.6.0
    osa_release: 00d84d91c488e4e92b3cc552bec6ebb9dd20e38d
    rpc_release: r16.1.0
