rpc_product_releases:
  master:
    maas_release: master
    openstack_ansible_ops: master
    osa_release: master
    rpc_release: master
  newton:
    maas_release: 1.7.0
    openstack_ansible_ops: d3b53d6f802259b5ea4d12f5a567a7ec86677087
    osa_release: 3553c048188093c7a8d912cc32c30730536d70d3
    rpc_release: r14.8.0
  ocata:
    maas_release: 1.4.0
    openstack_ansible_ops: d3b53d6f802259b5ea4d12f5a567a7ec86677087
    osa_release: stable/ocata
    rpc_release: r15.0.0
  pike:
    maas_release: 1.8.1
    openstack_ansible_ops: d3b53d6f802259b5ea4d12f5a567a7ec86677087
    osa_release: f4c7cd442cedf723792ec4c01dd64c041129c0f8
    rpc_release: r16.2.9
  queens:
    maas_release: 1.7.4
    openstack_ansible_ops: d3b53d6f802259b5ea4d12f5a567a7ec86677087
    osa_release: d38e190e43dfb737e6684096084b9f98f89e0637
    rpc_release: r17.0.2
  rocky:
    maas_release: 1.7.5
    openstack_ansible_ops: d3b53d6f802259b5ea4d12f5a567a7ec86677087
    osa_release: 9e72443b0d0a2e72f85419ae3aba94dee22f1436
    rpc_release: r18.0.0
