rpc_product_releases:
  master:
    maas_release: master
    osa_release: master
    rpc_release: master
  newton:
    maas_release: 1.7.0
    osa_release: 3553c048188093c7a8d912cc32c30730536d70d3
    rpc_release: r14.8.0
  ocata:
    maas_release: 1.7.0
    osa_release: fcfd8e267011d040dba722201fea2a3ae31ec503
    rpc_release: r15.0.0
  pike:
    maas_release: 1.7.0
    osa_release: 4e73c62c8a83ffc86f4ba0db8a2a616d04caab0e
    rpc_release: r16.2.0
  queens:
    maas_release: 1.7.1
    osa_release: aed999de3856ac496387510cbb48b7c2c11ccdd7
    rpc_release: r18.0.0
