rpc_product_releases:
  master:
    maas_release: master
    osa_release: master
    rpc_release: master
  newton:
    maas_release: 1.4.0
    osa_release: 32230e8cd982367940a9b68f65f1e73d6f14d2c4
    rpc_release: r14.6.0
  ocata:
    maas_release: 1.4.0
    osa_release: stable/ocata
    rpc_release: r15.0.0
  pike:
    maas_release: 1.7.3
    osa_release: 5c341a7bada78edab5f3d132d55adb00eaf2413f
    rpc_release: r16.2.2
