rpc_product_releases:
  master:
    maas_release: master
    osa_release: master
    rpc_release: master
  newton:
    maas_release: 1.4.0
    osa_release: 32230e8cd982367940a9b68f65f1e73d6f14d2c4
    rpc_release: r14.6.0
  ocata:
    maas_release: 1.4.0
    osa_release: stable/ocata
    rpc_release: r15.0.0
  pike:
    maas_release: 1.7.8
    osa_release: 7b692ea674e298b7cf856c3e1a0f6269cfa0f4fb
    rpc_release: r16.2.6
  queens:
    maas_release: 1.7.4
    osa_release: d38e190e43dfb737e6684096084b9f98f89e0637
    rpc_release: r17.0.2
  rocky:
    maas_release: 1.7.5
    osa_release: 9e72443b0d0a2e72f85419ae3aba94dee22f1436
    rpc_release: r18.0.0
