rpc_product_releases:
  master:
    maas_release: master
    openstack_ansible_ops: master
    osa_release: master
    rpc_release: master
  newton:
    maas_release: 1.7.0
    openstack_ansible_ops: d3b53d6f802259b5ea4d12f5a567a7ec86677087
    osa_release: 3553c048188093c7a8d912cc32c30730536d70d3
    rpc_release: r14.8.0
  ocata:
    maas_release: 1.7.0
    openstack_ansible_ops: d3b53d6f802259b5ea4d12f5a567a7ec86677087
    osa_release: 5047124f1fe181306674c60beeccd189252a9d62
    rpc_release: r15.0.0
  pike:
    maas_release: 1.7.0
    openstack_ansible_ops: d3b53d6f802259b5ea4d12f5a567a7ec86677087
    osa_release: 5c341a7bada78edab5f3d132d55adb00eaf2413f
    rpc_release: r16.2.0
  queens:
    maas_release: 1.8.1
    openstack_ansible_ops: d3b53d6f802259b5ea4d12f5a567a7ec86677087
    osa_release: 18be178679fea5f6c32e306ca07b0540cc7cf90d
    rpc_release: r17.1.6
