rpc_product_releases:
  master:
    maas_release: master
    osa_release: master
    rpc_release: master
  newton:
    maas_release: 1.7.0
    osa_release: 3553c048188093c7a8d912cc32c30730536d70d3
    rpc_release: r14.8.0
  ocata:
    maas_release: 1.7.0
    osa_release: 5047124f1fe181306674c60beeccd189252a9d62
    rpc_release: r15.0.0
  pike:
    maas_release: 1.7.0
    osa_release: 5c341a7bada78edab5f3d132d55adb00eaf2413f
    rpc_release: r16.2.0
  queens:
    maas_release: 1.7.6
    osa_release: e64fa56cf838c8a2391266ba69e46d8c4c857b08
    rpc_release: r17.1.1
  rocky:
    maas_release: 1.7.5
    osa_release: 9e72443b0d0a2e72f85419ae3aba94dee22f1436
    rpc_release: r18.0.0
