---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# SQLAlchemy/Olso Thread Pool Settings
rpc_conn_pool_size: 180
rpc_response_timeout: 180
rpc_thread_pool_size: 180
db_max_overflow: 60
db_max_pool_size: 120
db_pool_timeout: 60

cinder_rpc_executor_thread_pool_size: "{{ rpc_thread_pool_size }}"
cinder_rpc_response_timeout: "{{ rpc_response_timeout }}"

keystone_database_max_pool_size: "{{ db_max_pool_size }}"
keystone_database_pool_timeout: "{{ db_pool_timeout }}"

neutron_api_workers: 64
neutron_rpc_conn_pool_size: "{{ rpc_conn_pool_size }}"
neutron_rpc_response_timeout: "{{ rpc_response_timeout }}"
neutron_rpc_thread_pool_size: "{{ rpc_thread_pool_size }}"
neutron_db_max_overflow: "{{ db_max_overflow }}"
neutron_db_max_pool_size: "{{ db_max_pool_size }}"
neutron_db_pool_timeout: "{{ db_pool_timeout }}"

nova_rpc_conn_pool_size: "{{ rpc_conn_pool_size }}"
nova_rpc_response_timeout: "{{ rpc_response_timeout }}"
nova_rpc_thread_pool_size: "{{ rpc_thread_pool_size }}"
nova_db_max_overflow: "{{ db_max_overflow }}"
nova_db_max_pool_size: "{{ db_max_pool_size }}"
nova_db_pool_timeout: "{{ db_pool_timeout }}"
nova_api_db_max_overflow: "{{ db_max_overflow }}"
nova_api_db_max_pool_size: "{{ db_max_pool_size }}"
nova_api_db_pool_timeout: "{{ db_pool_timeout }}"
nova_cpu_allocation_ratio: 2.0
nova_ram_allocation_ratio: 1.0

# Nova config overrides
# NOTE: Due to a bug with nova, this variable cannot be set to true
# if the environment needs to be able to boot an instance from
# a volume
# https://bugs.launchpad.net/nova/+bug/1648324
nova_cross_az_attach: False
nova_console_type: novnc

# RabbitMQ overrides
rabbitmq_ulimit: 65535

# Set RabbitMQ message replication count to 2
# The desired setting would be {{ (groups.rabbitmq|length /2 +1)|round(0,'floor') |int }}
# but can't be used due to https://github.com/ansible/ansible/issues/9362
rabbitmq_policies:
  - name: "HA"
    pattern: '^(?!amq\.).*'
    tags:
      ha-mode: exactly
      ha-params: 2
      ha-sync-mode: automatic



# Memcached overrides
# https://github.com/rcbops/rpc-openstack/issues/1048
# memcached_memory is calculated via https://github.com/openstack/openstack-ansible-memcached_server/blob/master/defaults/main.yml#L33
# based on container memory but this determination it not necessarily correct,
# since memory utilization is primarily driven by the objects placed in memcached.
memcached_connections: 16384

# Galera overrides
galera_cluster_name: rpc_galera_cluster

## Enable Neutron l2_population
# We are overriding the default value for neutron_l2_population. Please see
# https://github.com/rcbops/rpc-openstack/issues/973 for further details.
neutron_l2_population: True

# Based on https://github.com/rcbops/rpc-openstack/issues/1149
# L3HA has to be disabled until all major issues are fixed.
neutron_neutron_conf_overrides:
  DEFAULT:
    l3_ha: False

#Set the default for Neutron-HA-tool to true
neutron_legacy_ha_tool_enabled: true

repo_build_upper_constraints_overrides:
  # Due to https://bugs.launchpad.net/ceilometer/+bug/1660800, gnocchiclient
  # must be pinned to < 3.0.0. This constraint matches what is defined in
  # the optional dependencies specfied here:
  # https://github.com/openstack/ceilometer/blob/stable/newton/setup.cfg#L36
  - "gnocchiclient>=2.2.0,<3.0.0"

# Increase interval between checks after container start.
# Reduces the "Wait for container ssh" error.
ssh_delay: 60

# Use the correct secrets file
osa_secrets_file_name: "user_osa_secrets.yml"

# Disable glance image cache
glance_flavor: keystone
glance_glance_api_conf_overrides:
  DEFAULT:
    image_cache_dir: None

# Elasticsearch global variables
elasticsearch_http_port: 9200
elasticsearch_tcp_port: 9300

# Adding elastic search and kibana to haproxy_extra_services
haproxy_extra_services:
  - service:
      haproxy_service_name: elasticsearch
      haproxy_backend_nodes: "{{ groups['elasticsearch_all'] | default([]) }}"
      haproxy_ssl: False
      haproxy_port: "{{ elasticsearch_http_port }}"
      haproxy_balance_type: http
      haproxy_backend_options:
        - "forwardfor"
        - "httpchk /healthcheck"
        - "httplog"
  - service:
      haproxy_service_name: elasticsearch-tcp
      haproxy_backend_nodes: "{{ groups['elasticsearch_all'] | default([]) }}"
      haproxy_port: "{{ elasticsearch_tcp_port }}"
      haproxy_balance_type: tcp
  - service:
      haproxy_service_name: kibana_ssl
      haproxy_ssl: False
      haproxy_backend_nodes: "{{ groups['kibana_all'] | default([]) }}"
      haproxy_port: 8443
      haproxy_balance_type: tcp
      haproxy_backend_options:
        - "ssl-hello-chk"

# Do not run tempest as part of setup-openstack. Instead, tempest is run in deploy.sh
# so we can control when to run it apart from setup-openstack.yml
# See https://github.com/openstack/openstack-ansible/blob/485100fbd36adbacd6f300a34a6acd9df3fd5932/playbooks/setup-openstack.yml#L40
tempest_install: no
tempest_run: no
