---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# TODO(evrardjp): Move back to the previous commit with os_ module in
# a more recent branch, with compatible requirements AND playbook
# will be targetting to good hosts directly.
- name: Add default flavors
  shell: |
    openstack --os-cloud default flavor create --ram {{ item.RAM }} --disk {{ item.Disk }} --vcpus {{ item.VCPUs }} --public {{ item.Name }}
  register: flavor_create
  failed_when:
    - flavor_create.stderr.find('already exists') == -1
    - flavor_create.rc != 0
  changed_when:
    - flavor_create.rc == 0
  with_items:
    - { Name: 'm1.tiny', VCPUs: '1', Disk: '1', RAM: '512' }
    - { Name: 'm1.small', VCPUs: '1', Disk: 20, RAM: '2048' }
    - { Name: 'm1.medium', VCPUs: '2', Disk: '40', RAM: '4096' }
    - { Name: 'm1.large', VCPUs: '4', Disk: '80', RAM: '8192' }
    - { Name: 'm1.xlarge', VCPUs: '8', Disk: '160', RAM: '16384' }
