---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Merge regular expressions for excluded checks/alarms into a single
# regular expression string. If the lists are empty, use '^$' as the regular
# expression since it does not match anything.
- name: Gather regular expressions for excluded checks and alarms
  set_fact:
    maas_excluded_checks_regex: "{{ (maas_excluded_checks | length > 0) | ternary('('+maas_excluded_checks | join(')|(')+')', '^$') }}"
    maas_excluded_alarms_regex: "{{ (maas_excluded_alarms | length > 0) | ternary('('+maas_excluded_alarms | join(')|(')+')', '^$') }}"

- include: host_setup.yml
  when: >
    inventory_hostname in groups['hosts']

- include: keystone_user.yml
  when:
    - groups['utility']|length > 0
    - inventory_hostname == groups['utility'][0]

- include: rabbitmq_user.yml
  when:
    - groups['rabbitmq_all']|length > 0
    - inventory_hostname == groups['rabbitmq_all'][0]

- include: create_my_cnf.yml
  when:
    - inventory_hostname in groups['galera']

- include: host_monitoring.yml
  when:
    - inventory_hostname in groups['hosts']

- include: network.yml
  when:
    - network_checks_list|length > 0
    - inventory_hostname in groups['hosts']

- include: kernel.yml

- include: process.yml

- include: local.yml
  vars:
    internal_vip_address: "{{ internal_lb_vip_address }}"

- include: swift_access_check.yml
  when:
    - swift_accesscheck_enabled | bool
    - groups['swift_proxy']|length > 0
    - inventory_hostname == groups['swift_proxy'][0]

- include: remote.yml
  vars:
    ip_address: "{{ maas_external_ip_address }}"
  when:
    - remote_check == true

- include: ensure_local_checks.yml
  vars:
    checks: "{{ cinder_vg_checks_list }}"
  when:
    - cinder_backends is defined
    - cinder_backends['lvm'] is defined

- include: swift.yml
  vars:
    external_vip_address: "{{ maas_external_ip_address }}"
  when:
    - groups['swift_all']|length > 0
    - inventory_hostname in groups['swift_all']

- include: ceph.yml
  when:
    - groups['ceph_all'] is defined
    - groups['ceph_all']|length > 0
    - inventory_hostname in groups['ceph_all']

- include: magnum.yml
  when:
    - groups['magnum_all'] is defined
    - groups['magnum_all']|length > 0
    - inventory_hostname in groups['magnum_all']

- include: container-storage-checks.yml
  when:
    - inventory_hostname in groups['hosts']

- include: restart_raxmon.yml
  when:
    - inventory_hostname in groups['hosts']
