---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Ensure container packages are installed
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 600
  with_items: "{{ maas_apt_packages }}"

- name: Install requires pip packages
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: "{{ pip_install_options | default('') }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ maas_requires_pip_packages }}"

- name: Update pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ maas_venv_enabled | bool | ternary(maas_venv, omit) }}"

- name: Install pip packages to venv
  pip:
    name: "{{ item }}"
    state: present
    extra_args: "{{ pip_install_options | default('') }}"
    virtualenv: "{{ maas_venv_enabled | bool | ternary(maas_venv, omit) }}"
  register: install_pip_packages
  until: install_pip_packages|success
  retries: 5
  delay: 2
  with_items: "{{ maas_pip_packages }}"

- name: Install pip packages for containers to venv
  pip:
    name: "{{ item }}"
    state: present
    extra_args: "{{ pip_install_options | default('') }}"
    virtualenv: "{{ maas_venv_enabled | bool | ternary(maas_venv, omit) }}"
  register: install_pip_container_packages
  until: install_pip_container_packages|success
  retries: 5
  delay: 2
  with_items: "{{ maas_pip_container_packages }}"
  when:
    - inventory_hostname in groups['lxc_hosts']
