---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Configure the default apt sources for RPC-O
  hosts: "{{ apt_target_group | default('hosts') }}"
  user: root
  pre_tasks:

    - name: Determine the existing Ubuntu repo configuration
      shell: 'grep -oP "^deb \K(\[?.*\]?.*ubuntu\S*\/?)(?= {{ ansible_distribution_release }} main)" /etc/apt/sources.list'
      register: _ubuntu_repo
      when:
        - host_ubuntu_repo is not defined
      changed_when: false
      delegate_to: "{{ physical_host | default(omit) }}"

    - name: Set host_ubuntu_repo fact
      set_fact:
        host_ubuntu_repo: "{{ _ubuntu_repo.stdout_lines[0] }}"
      when:
        - host_ubuntu_repo is not defined
        - _ubuntu_repo.stdout_lines is defined

    - name: Replace the apt sources file with our content
      template:
        src: configure-apt-sources.j2
        dest: "/etc/apt/sources.list"
        backup: yes
      register: apt_sources_configure
      tags:
        - always

    - name: Update apt-cache
      apt:
        update_cache: yes
      when:
        - apt_sources_configure is defined
        - apt_sources_configure | changed
      tags:
        - always

  roles:
    # We execute the pip_install role here to ensure that all
    # hosts have the correct rpco repo configured now that
    # /etc/apt/sources.list has been changed to no longer
    # include the updates repo.
    - role: "pip_install"
      pip_lock_to_internal_repo: False
      pip_upstream_url: "{{ rpco_mirror_base_url }}/os-releases/{{ rpc_release }}/{{ os_distro_version }}/get-pip.py"
      pip_install_upper_constraints: "{{ rpco_mirror_base_url }}/os-releases/{{ rpc_release }}/{{ os_distro_version }}/requirements_absolute_requirements.txt"
