---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather mons facts for ceph.conf template
  include: gen-facts.yml

- name: Install Ceph dependencies
  hosts: osds_all:mons_all:&hosts
  roles:
    - role: ceph.ceph-common

- name: Install MaaS
  hosts: hosts:all_containers
  user: root
  pre_tasks:
    # This is needed to set the rpc_openstack_repo and rpc_release variables
    # correctly
    - name: Discover rpc-openstack version
      git_repo_info:
        path: "/opt/rpc-openstack"
      delegate_to: localhost
      run_once: true
    - name: Display rpc_release variable
      debug: var=rpc_release
      run_once: true
  roles:
    - { role: "rpc_maas", tags: [ "maas-setup" ] }
