---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Nova config overrides
nova_console_type: novnc

# Set RabbitMQ message replication count to 2
# The desired setting would be {{ (groups.rabbitmq|length /2 +1)|round(0,'floor') |int }}
# but can't be used due to https://github.com/ansible/ansible/issues/9362
rabbitmq_policies:
  - name: "HA"
    pattern: '^(?!amq\.).*'
    tags:
      ha-mode: exactly
      ha-params: 2
      ha-sync-mode: automatic

# Memcached overrides
# https://github.com/rcbops/rpc-openstack/issues/1048
# memcached_memory is calculated via https://github.com/openstack/openstack-ansible-memcached_server/blob/master/defaults/main.yml#L33
# based on container memory but this determination it not necessarily correct,
# since memory utilization is primarily driven by the objects placed in memcached.
memcached_connections: 16384

# Galera overrides
galera_cluster_name: rpc_galera_cluster

## Enable Neutron l2_population
# We are overriding the default value for neutron_l2_population. Please see
# https://github.com/rcbops/rpc-openstack/issues/973 for further details.
neutron_l2_population: True

# Based on https://github.com/rcbops/rpc-openstack/issues/1149
# L3HA has to be disabled until all major issues are fixed.
neutron_neutron_conf_overrides:
  DEFAULT:
    l3_ha: False

#Set the default for Neutron-HA-tool to true
neutron_legacy_ha_tool_enabled: true

# Increase interval between checks after container start.
# Reduces the "Wait for container ssh" error.
ssh_delay: 60

# Use the correct secrets file
osa_secrets_file_name: "user_osa_secrets.yml"

# Disable glance image cache
glance_flavor: keystone
glance_glance_api_conf_overrides:
  DEFAULT:
    image_cache_dir: None

# Elasticsearch global variables
elasticsearch_http_port: 9200
elasticsearch_tcp_port: 9300

# Adding elastic search and kibana to haproxy_extra_services
haproxy_extra_services:
  - service:
      haproxy_service_name: elasticsearch
      haproxy_backend_nodes: "{{ groups['elasticsearch'] | default([]) }}"
      haproxy_ssl: True
      haproxy_port: 9201
      haproxy_backend_port: 9200
      haproxy_balance_type: http
      haproxy_backend_options:
        - "httpchk"
      haproxy_enabled: "{{ groups['elasticsearch'] is defined and groups['elasticsearch'] | length > 0 }}"
  - service:
      haproxy_service_name: kibana_ssl
      haproxy_backend_nodes: "{{ groups['kibana'] | default([]) }}"
      haproxy_ssl: True
      haproxy_port: 8443
      haproxy_backend_port: 81
      haproxy_balance_type: http
      haproxy_backend_options:
        - "httpchk"
      haproxy_enabled: "{{ groups['kibana'] is defined and groups['kibana'] | length > 0 }}"

# Define the distro version globally
repo_build_os_distro_version: "{{ (ansible_distribution | lower) | replace(' ', '_') }}-{{ ansible_distribution_version.split('.')[:2] | join('.') }}-{{ ansible_architecture | lower }}"

# RI-357 Tempest Overrides
# TODO(d34dh0r53): Once the test_minimum_basic_scenario is working we can remove
# this
tempest_test_whitelist:
  - "{{ (tempest_service_available_ceilometer | bool) | ternary('tempest.api.telemetry', '') }}"
  - "{{ (tempest_service_available_heat | bool) | ternary('tempest.api.orchestration.stacks.test_non_empty_stack', '') }}"
  - "{{ (tempest_service_available_nova | bool) | ternary('tempest.scenario.test_server_basic_ops', '') }}"
  - "{{ (tempest_service_available_swift | bool) | ternary('tempest.scenario.test_object_storage_basic_ops', '') }}"
  - "{{ (tempest_volume_backup_enabled | bool) | ternary('tempest.api.volume.admin.test_volumes_backup', '') }}"
  - "{{ (tempest_volume_multi_backend_enabled | bool) | ternary('tempest.api.volume.admin.test_multi_backend', '') }}"
