---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Configure the default apt sources for RPC-O
  hosts: "{{ apt_target_group | default('hosts') }}"
  environment: "{{ deployment_environment_variables | default({}) }}"
  user: root
  gather_facts: true
  pre_tasks:
    - name: Ensure local facts directory exists
      file:
        path: "/etc/ansible/facts.d"
        state: directory
        group: "root"
        owner: "root"
        mode:  "0755"
        recurse: no

    - name: initialize local facts
      ini_file:
        dest: "/etc/ansible/facts.d/rpc_openstack.fact"
        section: "rpc_artifacts"
        option: initialized
        value: true

    - name: Check for artifacts
      uri:
        url: "{{ rpco_mirror_base_url }}/apt-mirror/integrated/dists/{{ rpc_release }}-{{ ansible_distribution_release }}/Release"
        method: HEAD
      failed_when: false
      register: check_artifacts

    - name: Set artifacts found
      set_fact:
        apt_artifact_found: "{{ check_artifacts.status == 200 }}"

    - name: Set artifacts enabled
      set_fact:
        apt_artifact_enabled: "{{ apt_artifact_found | bool }}"
      when:
        - apt_artifact_enabled is undefined

    - name: Check if artifacts are enabled but not found
      fail:
        msg: |
          The apt artifacts are enabled but not found. The deployment has
          halted. Please check the artifacts repository is online and available
          before continuing.
      when:
        - apt_artifact_enabled | bool
        - not apt_artifact_found | bool
      tags:
        - always

  tasks:
    - name: Sync artifact files (all)
      copy:
        src: "{{ item }}"
        dest: "/etc/openstack_deploy/group_vars/all/{{ item | basename }}"
      with_items:
        - files/apt.yml
        - files/maas.yml
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Determine the existing Ubuntu repo configuration
      shell: 'sed "s/^[ \t]*//" /etc/apt/sources.list | grep -oP "^deb \K(\[?.*\]?.*ubuntu\S*\/?)(?= {{ ansible_distribution_release }} main)"'
      register: _ubuntu_repo
      changed_when: false
      delegate_to: "{{ physical_host | default(omit) }}"
      when:
        - host_ubuntu_repo is not defined
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Set host_ubuntu_repo fact
      set_fact:
        host_ubuntu_repo: "{{ _ubuntu_repo.stdout_lines[0] }}"
      when:
        - host_ubuntu_repo is not defined
        - _ubuntu_repo.stdout_lines is defined
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Replace the apt sources file with our content
      copy:
        content: |
          # Base repository
          deb {{ host_ubuntu_repo }} {{ ansible_distribution_release }} main universe
        dest: "/etc/apt/sources.list"
        backup: yes
      register: apt_sources_configure
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Create the rpco apt sources file
      copy:
        content: |
          # RPC-OpenStack repository
          deb {{ rpco_mirror_base_url }}/apt-mirror/integrated/ {{ rpc_release }}-{{ ansible_distribution_release }} main
        dest: "/etc/apt/sources.list.d/rpco.list"
        backup: yes
      register: apt_sources_configure_rpco
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Add rpco keys
      apt_key:
        url: "{{ rpco_mirror_base_url }}/apt-mirror/rcbops-release-signing-key.asc"
        state: "present"
      register: add_keys
      until: add_keys | success
      retries: 5
      delay: 2
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Remove extra sources
      lineinfile:
        path: /etc/apt/sources.list
        state: absent
        regexp: "{{ item }}"
      with_items:
        - "^deb-src"
        - "-backports"
        - "-security"
        - "-updates"
      when:
        - apt_artifact_found | bool
        - apt_artifact_enabled | bool

    - name: Update apt-cache
      apt:
        update_cache: yes
      when:
        - (apt_artifact_found | bool) and (apt_sources_configure | changed or apt_sources_configure_rpco | changed)
        - apt_artifact_enabled | bool

  post_tasks:
    - name: Set artifact local fact
      ini_file:
        dest: "/etc/ansible/facts.d/rpc_openstack.fact"
        section: "rpc_artifacts"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
        - { option: "apt_artifact_enabled", value: "{{ apt_artifact_enabled }}" }
        - { option: "apt_artifact_found", value: "{{ apt_artifact_found }}" }
